ingress:
  tls:
    - hosts:
        - allure.localhost
  hosts:
    - host: allure.localhost
      paths:
        - path: /
          pathType: Prefix

image:
  repository: "registry.localhost:5432/allure-test"
  tag: latest
