apiVersion: v1
kind: Secret
metadata:
  name: arc-github-secret
  namespace: arc-runners-local
data:
  token: ENC[AES256_GCM,data:HiplyJxUpHLTN7CtKDuTLJI1Dzu7aJu4UBt4LldM5g+xq+8cn7dOWJOYZd8Y5Y09oqCgicq91FI=,iv:xyjzLeDdYIXnL4OijG6SlD1PdyR+pO2zncYitWA0fPA=,tag:2D3i+evaTmD1SfSae4T5nw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSBHMzha
        V01ZMHVDVkhHZk9Zb0s3MnJlbDA5cElHNk5kYmx5YmExdXBONFFZCmtScGI5RkVq
        L1g2d1NBNGZDS2QzUGREVmI3bVBvbDc5MFdtbFlrNUNmOXMKLS0tIGd0aGpNWU5Z
        TkM4S3haR2NrUlk1TjIyN0RHUHM3QU5rajluYitHZThTdlkKo4m/J6Ch0ycPP2L1
        u15vTNiApOscXT6uDoB5lVJwrkESkYso9D/+fUAAodUr3M0oPlCia3Od1K6rASHZ
        nTQCeA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYnVLYjYzdzVHZzhkWXF6
        ZHpNVFAvKzhwUko2L3NXWnVVQVJZSjNZRUJBCjR4NDhoajdWejJjcDBFR3lmYTdq
        ZElxUDVsZGhSbzV1ZENOUWZtMUFnVXcKLS0tIENSUDU1ZlVVUUI2SFlGRENJYjNT
        cTBuK0Z3TTFSWmp6RFJFd05pbGJTR0EKWAQHfahSEecZMMRniLJdRK4TtVb8txcX
        BpBk4sZ31D+ycwHuhkmAbS7cTtuHUXidQr18EpWHM+Ms45BbYQPtlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-23T13:09:24Z"
  mac: ENC[AES256_GCM,data:qOy/7fBfwLRKpieY4kWbq+GUroa/FnslWva4aj/lKOal3l+LVPnVboPpQu/QGqWA+H1HqtWC5b70HOS0Yk6N1UYyM8CiTmSjf/iDe7nDW3wzUOQMWMgSC70Iuc6kE2X4js++7emgRDS4oDTK3bERDltf13w/XAFsUal5T6tE0hs=,iv:0cYtsEGXuphljMxnHZRFGK/G61hnTqaVQ/3Zl79QtdQ=,tag:jmId+Sp/8YVeMI/UEnHoWQ==,type:str]
  version: 3.13.2
