apiVersion: v1
kind: Secret
metadata:
  name: arc-github-secret
  namespace: arc-runners-local
data:
  token: ENC[AES256_GCM,data:HiplyJxUpHLTN7CtKDuTLJI1Dzu7aJu4UBt4LldM5g+xq+8cn7dOWJOYZd8Y5Y09oqCgicq91FI=,iv:xyjzLeDdYIXnL4OijG6SlD1PdyR+pO2zncYitWA0fPA=,tag:2D3i+evaTmD1SfSae4T5nw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSBxR1JM
        cTViS0JGSk5vc3NlWXYycHZOQjFHQWt6b3Bld0IzY2pBRVNkaDNJCldwNWdKTnEx
        bEtLblNIeTNiWTFFd09zSXdXT2JZVDJVaHRtRUdWYTFQa28KLS0tIHhIUlNRVlNH
        bXNMTlZyWnlwc0pHUFpZNk9URDZhcTlFNS9TY3NlR3NOOHcKA9kEiaFz7t8YgH7G
        XPVUb0oHCeq3dv6VOm+NbGqwMPF1OyXN4KBqG+3jWAAasroc5sx5s57xus+2K9sn
        QF8Cvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyBKZFU2
        S1NMdGptQTVGVEpBUzgydUloQWRIdU10SmViNTlSWVptRXh1bFdjCm91L2ZCRmtS
        aUtqT2d6NVJVOG40SUlqYzFGUzZudXZyOVNXcmJ0TGFkRUEKLS0tIDIrSW5lZzVx
        MXU1TEFQeURzRk1LTmFEOWc0Q3NWcmhPM1U0Um5xZjFFWUUKP7yY5sMxjOA3wJCZ
        iSL2hXqgPVdsy+vGggWRwSyATptiYHenj+bUutTo8maJGycggVJUKMSvJcm4uusE
        D9SMGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyBGL1FU
        bGJPZVNreGRHQ1dET0dNRktqeG8zM3JTL0lZdTRDTWQ1TE1oY2lnClRkd2thR2N1
        ZUIxK2xpUGRoR25VU1ZRQUNqQTNnNDFQTmVPVXZoSFlaWFkKLS0tIFVWUjlGbkgy
        V0hNNUZIdzVaR3hSRit1Y082Y3k1WUdKOFpQVFVQaTV6ZmsKm7TnNewHI7qwzuBh
        TALUfa2TBEa8BjVa0wGT4gVTKuY0aEJ1dYuYVPcEqJmnB/wDP15nO9PsU1mnRSFK
        ORDhiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdHdsY1JLRGZRemRidzJx
        VXBuQS83cHVRZ3BBTSt2VzlGZ3g3cmY0alhjCnN5d3VuOWdwTVdIOEhuTGg1eUlW
        Uk5oMms3bDVyNnMwOFRPSkVYeXpobzQKLS0tIGpMLzlUbEVBa3cvRmNpWlk5OUpu
        NUpKWnFpYnlQM1FOTkp2dTIyTVl1L2sKHQeYThljG/2JP7LbY/vPLc4BVSWYK3lm
        R90R3Lc9lhz+GruQ4lIKbq8+HYjThwQ5wfY7MzBnzwJsSo1pnrJ5UA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-23T13:09:24Z"
  mac: ENC[AES256_GCM,data:qOy/7fBfwLRKpieY4kWbq+GUroa/FnslWva4aj/lKOal3l+LVPnVboPpQu/QGqWA+H1HqtWC5b70HOS0Yk6N1UYyM8CiTmSjf/iDe7nDW3wzUOQMWMgSC70Iuc6kE2X4js++7emgRDS4oDTK3bERDltf13w/XAFsUal5T6tE0hs=,iv:0cYtsEGXuphljMxnHZRFGK/G61hnTqaVQ/3Zl79QtdQ=,tag:jmId+Sp/8YVeMI/UEnHoWQ==,type:str]
  version: 3.13.2
