apiVersion: v1
kind: Secret
metadata:
  name: arc-github-secret
  namespace: arc-runners-local
data:
  github_token: ENC[AES256_GCM,data:V6GtSphx2dDhC0X+NnTCSxxMF4fKVIOYbd33Jx7u43Uus+MEnVqa+Rhez+U8bgkTcGpZg1UTujc=,iv:GrdlaxSZBr/gHfC9Rxm6I2/SpHsARPG9nyG7/X2Xgeg=,tag:AE3f7jRXK/X0moSNkxnXIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSBTcFE5
        ZUhSQUpGNEN6SEZBVnpwWTJraXgvdm9vUUZJVW1DcmJ1N3FINWhjCnYrQysyUjl6
        MlZiOXBtbzluOW5aY2kzVGU4cGtSdzRtUnFPYW9SdzJTWTgKLS0tIEx2Y3U2NWNt
        OXNBbnhDVWdLalNxb1FqNVQ3dGJrZlZuUXZNdzh4NEVCNjQKJe2Rf2kbCqTxPMxr
        /yFmQ5UC2kMyExv4inOJqJ7a6scTekpevhxeEwDEHdSwI/u5hJkSf1cIV3xWnp+j
        fjlsxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyBwTjFp
        RXU5SW9XK1dHWE1FRnRhSjhTM2c4WkVsaTc0VzhLb0oxMFp6N2hjCitHL1Q0QmNk
        ZkxZZTA5cFdxbm54RmVST3E3QlprMkw3emFpOUlnUE13c0kKLS0tIEQvR1pVYWF6
        U1liVWhPRklKbmdRdmlxNHF1a2Q5V05QU05qSnFRbzBaVncKwRSkz9+6N9JMOKsF
        LIdsvwbRqAkZl0hSl/avTBTPyezeURnPYeBBJ1FudQ0DGYky0cnoGBehI0POX0zw
        4EbUaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyBMSTFr
        cEZXaXBETTBHd3VFc3h3c2RYVVYreEVxczZmTE1wN3RBS0Q2c1RrCmhjWnU5T3Va
        TTRYVWxKRjE4dkRYTDFRb3hCaURVQ0R6bkxkek1kamNtRTAKLS0tIENuQnRKTEJR
        NXhJamNLZC9aQmFSVmZEdnBSOHcxMDl0MnBTb2RubjVwUW8KHng/V77iwNxYhRuX
        2xU7Hb7vIBYypriboymjO0oH1idhavkK1/YGjB9GRo1XPRHm9nHdaXGF1RqC7GyT
        gQH84A==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOEJsYU9UZVRsMTNlSHlo
        UnRFNkNXMTRBM3lWTHlRNU52QlVUcVI5bFFZCnd3QTBScDBKWGRpVm1tRTdTT0pJ
        S0cxcjNEVUlBbG9Cdm1SNGYzU2RKMWsKLS0tIC96OXhjS0xFTytyR1ByY1pXYUV6
        TkNtV1oxMVVsTENCemZBbFRLaktucVUKznO5N3Y+SkKehUjFbJvp8J95NBq3qZDZ
        3vvxpOjwEzHHuj5egfxnK6SDMps+WuxrI+JX9m3zQhDq1UVQ++35kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-23T13:46:52Z"
  mac: ENC[AES256_GCM,data:A5/AYWELYM3R+KQOzM6DrSCBT/4uim6Hz5fwwwpTT+qouoNcY/nmhasexVh0xQDrBX6/nKCw3+/cmnaTvg2lXnBXA2k7/PUpcBRxX5k+atLnmkbYB6s+68bb2HzBa7AIgIeFSgyLUU05YGaPibKtZZ8PxTYHMInkQWmDc+JZGbk=,iv:eAmkZ09FmoqUJAdu7WCtBQVysG06S9YV/nB0Ukqaotg=,tag:GkBqRU3/d9qTU5PqWuJHjg==,type:str]
  version: 3.13.2
