apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: /repos/github-token
          value: ENC[AES256_GCM,data:J7fAQeCJZVtuLYVJn9g93twDb+9nyZcxosKSySwagaQclSiPuI+557UjWPiGuRU1Eqi1nYLm89M=,iv:SBHRvKyBjmfIcDFpcEct6cNYIjKb3zU95I45xWSiysE=,tag:61EwUFVlzs33O1UG4iWBZw==,type:str]
          version: v1
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSB2eUg4
        NzJsSmFsK1ZKd01aVitkYldRblI3UW52T21aQTVQQ1JKMUhtMDNjCnVrYzlPclBm
        SU0vclZDRGtQRWI3WDlWbXRrRTJXYjQ1UGp5ZExPK2M1TWcKLS0tIHJKN01nTjRN
        SENWN05SRUdpZnAvbW1IdXFmRXgySXU1ME9sSS83dVBNRzQKRGMBcPUTeHGvxQul
        cBqZW3IH7tTCR7d04mutOOpRADZPrhxvA46VdykTSTmyJxHuuk3kRw3fKAevZWRr
        R4ZPxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyAxZmlY
        ZnBZZCttR0hwSUFSeTFzbW5kOWRFVnBKM3hkQXdaMTFydVR3TmxnCmF6QWRvL0Zy
        T3B0N2FXSDlnRTdwT2daa2NHekg1b3dEckxIZlhYK2xkOHMKLS0tIE9tK1NGTy93
        WWtBc2FiMmxieHlzOEtESHVOeWRlaEJQZ0NJNklibjlBUnMKHDUHThha0vI4qAL7
        Z2Met54ntSbl21er5LEW8v2+Wnv9WF0EmYiFgAuDoO7DULIv5dOadr2CZ4l7SoXQ
        OOgSWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyBIR1pS
        dkJ0eDAzcElZOSttL1lURU5BcnRpYkp5Z05FOXJmTWlObGxsS0dzClBRRGZ6ZXht
        OFhmRElTWC9XM20wWXRGK1RURE02T2xRcFJOa3dQbmoyWjgKLS0tIGE3d1pOU2lr
        Z2RXNENnNWJLcHhlajVTenpYbDdIYm0wZkp1b2VSejJRMG8KLjPtpI2qv0WbE8Qj
        V2lO4yl1hxBbCrG2/CjqTO2a37iy2qyFWvOAKejdI0ymODAd4Dsn6/XIfnNtEc20
        ZOsqsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSmlBcGpHMTVjQXhuTEpE
        dk5ibG54TXpzNkpMM3plaWlFNGF0Rmp2VmtrCkNZMlRDZ2ZGVUJWSk5kMUpKZXdp
        OEhPSTc5bGVaR09sM1Q5TVJNYjIvNkkKLS0tIHBHMjZncUVxNngrekpJRGdYbmJD
        M3BQN3Jkdkt2Z0RiY0JCc2UrVHJlS2MKBxzvEO50ka/Z1esaBaOsxWMRUZvPr9UR
        JXOdqlCadMGejcVHdqJR8ZeP+NYz6UFwf+OuR1guyZ3r1Qr4T8uBOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(value)$
  lastmodified: "2026-09-04T18:19:57Z"
  mac: ENC[AES256_GCM,data:o5EqIwr0+wU/w+rZB7xAiKq9mMmFegRc23RYv2POiWo2ZuzwefO/beJNJ7wj7L85j2LKecSj2mjTJBri+pOUwTIHE15x02LgrT07Z/cBG8gl56LGpPkLaGVl8MbLPV4l5gjm+Mdu1TArGeT2/Yq+8kO02FPhMBCnht+neBM6Ydo=,iv:2O65H9hJ46UzipI+Zcgr74QQJNgsx7pudSTbnye9TvE=,tag:LWYWvgFXqgJCxrIea0px4g==,type:str]
  version: 3.13.3
