apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: /repos/github-token
          value: ENC[AES256_GCM,data:USNn6tJStsvJerncfEP6RfU/Kr7zK7StD7Mg/LsntwZUYA9cGFa6/g==,iv:hJm+GOkD4Cg34v/6l3gFdt3Am5TsmpBoVPwNZGaN1TQ=,tag:rdBwz9a8uUFGFaH+omU3+w==,type:str]
        - key: /registries/nexus-cloud/username
          value: ENC[AES256_GCM,data:gDZdoXFRMJY=,iv:ygKO3KWBK+cA5R75aQIfgDudbWaH+7M5bplN+RIlv0g=,tag:8iV+YB+6jb7GvqDDhzimSw==,type:str]
        - key: /registries/nexus-cloud/password
          value: ENC[AES256_GCM,data:NvQbioRL/V/IcQR/PEHXhRYci8eEPWqjEnK/KmnF1XcwCawSZMG7WrS6WKA=,iv:/7aKv+VSLbEMMAsefrnoeZ5ZRpy4FNzA6hVcB4SHpwo=,tag:x97pbU1UJ9dgnG4c1B5iQA==,type:str]
        - key: /oauth/github/libra-hub/client-secret
          value: ENC[AES256_GCM,data:1dFlfWb/uWQRHv6BEFnbtwi1ulE55iFeZr24JUVN3TUa/c41qsOV2A==,iv:ITYrvSqO8nly2jnVl55RK2EbIZpWjJBiRwQPgB9qMbw=,tag:WUAeBJUyMrMvO4zSUt1z8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSA3SXhX
        elJZaWZxM3pYc0ZpZG9LU3FwbFQ4TnlzbWhKWlZLeE85VjlaMUZVCmJlZ0piY2lF
        VTRlTXhVZzErNG1DcGxlQXd1cDdOSmR2QWxBSTkyUTc3QUEKLS0tIC9laGZ5Y29p
        MmtCbWJhbnlwb1ptOU1iQ1VFeXBpRThYYXBSSHZlZlovQ2MKUQOmwuZzN+F5Igl6
        Ei63284zcMU+bAtSwhJF/lXeqctHFAC5MGj/MBoOMRU7eYNmAY+uYxpWg7C+sMaM
        c22w6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyBKNllN
        VVhYMjBwVGxRUGdaYS9QTCtvZ1U0U051TThLcmNlWVlxZlVDN1EwCm1xSXhtczBq
        YnltaTlEWjdwRXI3WHFocU10SWQxd0VOaFBWdkFsOTBMMWMKLS0tIDhaQnhCbXFT
        UlBtM1FoeERGS0o2c2VWVVRadDA0MVpIQ0o0TnlJa2tPcDgKgV9NBNmOT8IF1ddG
        5TmTG+mWe5poFx4lDD9bffLDuP5vyqUc+jN29ThunyOUsgOIIAeAPziamOqW5Jy/
        bBMnYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyBHVktV
        cE1BdkF3bXVIRkVRdWdaTjdldGJyUU1BZWJHNnB3R1N0alp3THlBCkMyRjBRT2VT
        WlBaRTRpMnNneVgwVUVSOXg1Ym8zazNvaHloeEFjRkNJWDgKLS0tIEttK3BHQVQ0
        NVVzdzJFL1Z4ck84d2xSeFQ1WnJxemY2c2VwNVJPY3FpVncKJgfa1Ii0SPra/MWO
        MTaGsEmdd6pCwiCbYWCwhskppV9P43geIhBcLTmDSPRjxxX9HIZt4vfuMSeToHga
        cJYT4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM1oyL2NlREZWZDMzV0g4
        VVhydDNST1pBQys2ZldaQWdHeGJFUFc3MXgwCkQ3YTVDWlVnRUhGWUhxS1JxVUd1
        RHRheStoQjRZN0UxcU9YaFhKTWtZLzgKLS0tIEJGMHZUZE56T0RsRzB3ZkJhSWk0
        L1VWWW9iYjR0OStsdFJzZ0R6eUhMaDgKWu36zmeEV95q7s8IDwNAR+xm/5U9SRJL
        QCnDMDU3OBZuhAY8eBkV3cYYJs9/qNAjT31T3jo2v4M7sXwzXxw6lQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(value)$
  lastmodified: "2026-09-22T13:56:46Z"
  mac: ENC[AES256_GCM,data:DxFSSi1FGaAHcAHnWl2vl0c9PkI4giJfGE43lWi+0NFqGGwYF+RTMivE2nio04F70cWNEf1GsHQp/ar0S6rMqthfAuIoyBNvdRxyoIOUfxuJhHXIZ/RIKBOVCHPxgcJSPAif2RHjjEjnbhwQYEnVSJlf24OipGBvjgVFtITuC6Y=,iv:N470S4fpxafVtFVEfU7aruM3WvMFzN+Vl735HQ2o+vU=,tag:dGQtSiX2xh65pKYPH+0uDA==,type:str]
  version: 3.13.3
