apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: /repos/github-token
          value: ENC[AES256_GCM,data:uW4NFzYcNDyg25bXvP74Jx7elEDPmgwUbzMF3JhkK5kJwbzMqnLmyg==,iv:5iQYNui0gZuaq2y+DTE7Ty0HywDHTnVhZYkoNIPl3nE=,tag:QcfPWsCfaXHdlmf5hIwbcQ==,type:str]
          version: v1
        - key: /registries/nexus-cloud/username
          value: ENC[AES256_GCM,data:O64mnU6IngY=,iv:qFXWgyDr1NyNTknYdLwlfbUKXFKr+MLGI9DI9FTnj4Q=,tag:OXZLrA65j89rtSVcEQ4+Qg==,type:str]
          version: v1
        - key: /registries/nexus-cloud/password
          value: ENC[AES256_GCM,data:hUMv8R7o9Jk7Y2FCs8gs0xE8jNEFWKBrHQSLTsyHU9LKBV6ZR9ig+isBtLU=,iv:KtU0xWtYJrNiFOdo5ez8OkE7KL9zjfGX4atEGD7ho44=,tag:eIrW7xnxqX6GPnqBV5nrKw==,type:str]
          version: v1
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSAvYkk1
        LzhuTEEyNWd4cTRiVExUNUlURTZRU0duOCszTGxUenczU1Y4UkZJCjE2WUZPUjFQ
        VHFyYXAxNXkzSm5RSmw1SFNrOVpJSXcrUURyclJvREtJOEUKLS0tIFdoc0tRclYv
        QkZ0amRWM0dlNVpMZTVtcjdUVWhIQ0dFandESFdvYllUS2cKwqVMxfIkAb+PURIk
        ad5kInJ6KEaK0vQv0e5izculY+HuJRkvMwMYjuagLOmz+RGrIN97dWdrl30TeGkr
        pMor4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyBMNjBD
        VmZCSDRKa2JVeDJGNkQxR3d1SHlIblFIYTF2LzVpWHJvZldGN1ZZClNodXJpL0d1
        clJXd09DZWk1ZzNkWjBZV2pIZTVON2oxYWJxSjMzd0lWY1UKLS0tIGV3ZTE2b2Jo
        czU4M09mWm5mOXJVMnJHMTh0ako4ekNaRVpMc1ppZ2pFN1EKDHvX4rfmV7hYxkN1
        IuoV+RvrWlBUVzWFyEoupkLd3HaUCmxBp8hk5cEdLlcZoxeSvB6viRPXXKeMB1o9
        RCNOfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyAyU3BN
        M2o2cEpTOEJsVXArWEk5TEc4a2lFMS9SNGtqKy9iVS9vLzNVUWlRCkhubFFuZUcz
        akEwd0hhYUxueUd6UXN3V1NtT0NHK1NnZDhqWFhEL0JWYTgKLS0tIGNSUmpTQ3hV
        NWErUTJLcXZiZjRTYy9QQm9IcjVBOXIrRXcyOVZ1UzRIbTAKbKXoyDlskJHfSdjU
        HTDnJkbvoUA0LkF9W2rUE2rpTTtqDiSDt6m7cx8p6uwLgjcFjwFaKqJzoa43qhPW
        jXpUkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaHljL3duMWRZbzVsUnEz
        THRyL04zZFZrMHBqNkNYb3BtZlF4OWFtdWlrCkVpSHo5QWtzZmpiK3JubzR4aFpH
        SGxKZ0JxSTREWm4zR2Z0VlFkd3NUeUkKLS0tIHdYRGdnVDVTMkZQN2NBNTF2UUVq
        eFk2aGtKYTFvZ3ZSbTNpTUpSQ0Q0STQKFZr/4TdJ/JjzwLKCAIoxIQTxqdX3FqK8
        ZZPMx47efZ5fCQyjDaKavJ8WSK6Bbx3P+gXRN9tjFNZXwJSnrBfb5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(value)$
  lastmodified: "2026-09-08T14:02:13Z"
  mac: ENC[AES256_GCM,data:CrgEp/BUe+Y3p0M0LyPhzZf9IXptgHtPSt9lwIz6zrUwDPE1jIBD5YDwg+kvAogX0ION5Nz1Yltvyn9cWo7kZpOhaQug9itH6SL7/id4w09dp5aKWifkEmqh6nmmAhCjn73JTyDDaHBLrXE+uLbTMsZVMnZs1xt+gF6Bs297hg0=,iv:uAlsXzus7L5iJ0JgVOK9XtgPbVhn8guzfzadQrbHe24=,tag:ORdX1fU+liRLAbAVLGGPnw==,type:str]
  version: 3.13.3
