apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: scm-creds
data:
  token: ENC[AES256_GCM,data:lOkH0ghs0xWiq4Y2sriFTsVP8qq3geWgJORbNqNf+Vavw650Qs9hmQNb2xj4i2jRFjuF1imEzvQ=,iv:njk8iv2KTPBfs0SmcwXq/yxk7WUV5WahsQgL87Ofq2o=,tag:kE58zU6lHvdDdsqXNbTjVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSBzR3hT
        ZEpqb1NHR2VoMWdYT0krT09tdHhXMW1GTXhTWTZBcnpsemJpWkFFCk8rdWFGdlBP
        eklvdHpHVjhmdVVteXY2UUhUWENLT1lhUFpHMEhMK1ZMWlEKLS0tIDZ1dnBkOWps
        QzRMUU9TUnVnQVZENG9RYkpUMk8wb1hHaUdGRDNvK2tPSlUK2RMhekVGUWq5fBmo
        9/lWqS3JrDgLILtLoZPKn1IthpViEejwxlGCZA5OMuR6xo+A0r8K9CurKhrrrqSN
        QONX5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyAzcElk
        K2pybnpaam01NWFhb1Jrb01jUkRocUU5TDc3bFBWV1JLTTJuZGl3CmV2MW10RkQ0
        NTN0dndnZGxOS2VqQkgreVVHby9ENVNCMXhyUHQzVUdseUkKLS0tIEI4WkpuMnIw
        bUp4KzZpZmwvOTFzS0RSaGxxTldZK05DaUFNZmVxbDRqN3cKbAvHwbT8cZ4miIEu
        YeJJfE2yxD5M11LL7sudGRfNX8s1J9B9GYPGZniXY6+IRr4BpvsZsv+ifhLxuR93
        UE15Rg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyB4VlM0
        dXhxMGtsTGhIcmQ0d04zb3ZyOXhvZzNlcEVTYUlsUU1EWWErNTBjClNTSE4vTjh3
        aUxPMngzOUFBU1lnTUdXMEhkNEg1aDJKZHlRRCs0Mm8vWGMKLS0tIEhoZVRQOEZs
        T2E5V3pYSVZXSSszK0MyaGw4Ymw0TFlaOTlpZHdGNjFzeXcKV3GjPJkZpYybEXQb
        yX7ZQ+3dBTBnmubpjZ4bDShnx0fMrRZDt9B/NCMFhULAGt3g+K4H23oPAaB2wLmc
        rP3oUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweXV3STVKWkMvQ0o4dTRY
        dU1Uc0ZjLzJ6cG90VTVXaHIxb1pRbC85dnprCjFVTmtyYkxzSUR3SG1NMTZIMHcr
        bS9GNGgxRUZuK3JHOTVKek1LcmtROUUKLS0tIDJqcmlDMWluZW02N2N1K3o3MUMz
        R3hDM1FYQUhKZWErOEJoSlV5MVNlcGcKE/BhSIZgtOMrX0agIo454jGsTiRd0vRR
        0RNeP2WA8bXmtKmdPvQjRhIZgD8daeCzkCXCBKq9rvD3uQrfDass5Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T18:47:46Z"
  mac: ENC[AES256_GCM,data:ahVcjUwpGlI3Oa5z/M+QcQj/6NEAwtohllv2VRD+YyWeqOREgCMFq97CCuYm13MiMuNOsPSDOGnZgEbYQLwaBz6mNb/ZgcJ9nnKGgIoIEvdwCCoY5jneoM1ga5RWcXHm6wSQ2kwEvlOaXdH9zHuHnUvsLSWx1LkjlbQcIrdBG0o=,iv:0KPtHYZOgv2MpntHQAeX5+B+k/alWgFM638WG2m4ZPc=,tag:xu/K5mtwTJ5wDc17Aq6rbg==,type:str]
  version: 3.13.3
