apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: scm-creds
data:
  token: ENC[AES256_GCM,data:mpvbz117IYsPlzIi1Fs5rzAOVBvUlz5Iw/cigir5qqBlh4zAbMNyBrv53/vgLaihryfLuQglVl8=,iv:zZVzZAQac92jb26MWJeiF+Zay6FVDjCdyJhuz3pvzlQ=,tag:P3N7V39YYkK2RnwKY1tGUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSBsMzQ1
        QlFRRS9SSG9qQjNBZ2xaTW5nS2dpTVZZMm9KT2dzbjhjYjQzczBZCk85ejg2NW9W
        SGVKZjNrd1pnenQyeFg0czRQSTJkTHJVbHcxbktqbXZ1Q3MKLS0tIHVRNTdnNWZU
        NTNQVmJWS1FHWnc4RlgyNFNnNG5JNW0rcEFmanFhY1A1bWMKTLOgZVKcw43YuUG5
        1b+psluI8BkshpdKD6qVlZOuK5eLkSih89vzVrLo3sNFWfKAWO+DMDLQ8X2RfWMg
        UUjAtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyBYUTho
        cnhzTTVFeTJCVEt0OWZMeERnYUlSdHVDVTExQWcrUWVSTjg4eVRrCkI0MDZORllz
        M1E5V3ZvdU5kdUVJT0hEaXU4cy9XTEV0b3lrQVJvUm5UbHMKLS0tIHRpV2dteExN
        VFJhdUY0dENsVko4TUkvMElSTUdMcG43Z251d1BDVUxtcU0KNfjeLz7NgpetWuwa
        fW4k6dS1Ba6mDIm8BOGar7Qpfwks5XW69mlWh2oXWeaYzog1OluFiKoZnVTjqzIU
        h5KKUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyBZelFO
        WlNDdE5KKzNSVkNVdFZvOXUrcHFLNThVVnEvVFRpNmIyazNJcGxvCmpzUjY2MDN5
        YjFybEZhSkdMdFAxVGM0N3RRUUFKQ1BFUm8rK2Eyc2VCUFUKLS0tIHlZTXNRSE5Y
        YzBUV3ZmWUV6K1Q1VTZNODVzZEN3VkdPVm9HV1dGNFhkbWsKH71QbXinnf7YNVCT
        6/WcEc0vvwJ1FJdp8zlYahwRHzXbLxPnIHEMmNFiDl21zw8D3DPnfwnbEB6vcZVS
        v042Dg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT0ZPN21RMHNhWVVsU2s4
        dGZpcnFyeExaMnJHdjVQTVlsdkhQV08zcW5JCmNYbTViYTRuNStJVUx4Tk80NEdM
        K0VabkR2TmJpa1I2RHVRekd1L044S1EKLS0tIFloM0VsTyszNkVhVjZ5S1M1LzQ1
        V1dXK01VdlZQTWlBV1g5RWg2ZjIydEEKTb2SFR1H2Bd4tffNX4ZQIBU6+hbUW5LD
        91w7UKZ9pDK6SS/eTR8V/cIORVuKQlhuTvllNbU5wAdyNgJSkj8+Bw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-04T19:05:09Z"
  mac: ENC[AES256_GCM,data:wvM9KgdJghj/0Brpk5aTsw+KYmaydlNOTadbB4eULRwV3FTeY4wzGLDlbtocFZ7P8UkPQYpy7JOT8h+DMgh7+/Ka8dtOeShGytrHrLa8CWJYsvfMUdzU9AvLAu2Q4+Tp7lWZGtk0Yj2y4hQ57n1u7p/XKCEIQP1Qb4N+d9nXfKE=,iv:DL2j9n4TR06vlqgQ/TGH0It8lMriGVosU54xhJ+txoA=,tag:TcJzzoOCDyI58XehWkxL/w==,type:str]
  version: 3.13.3
