apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
data:
  token: ENC[AES256_GCM,data:FBD8LM7JgdMwbZaAutBg518rci57mt1nkfpCgKv+ISfEVd7DzdK5MmJ1VH48kbeq3sgukI4Bgyg=,iv:wNvS3CpbGwS6ywH1993QB2Zhz8dtSUBum4DciYJpCyA=,tag:wO8Ip6N9eAh0MwkAeIfzEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSBKSkhE
        RlBOWkhYajZheDJOY1BoMlhKVTBPZUZXTG83ejRmeFBXQ2V5bkFnClZIUTVrR2Zm
        WnZYK3N1THllUzZsQ0wvcFlkcFhCWVlFV2NmMEY0SEpKMVUKLS0tIGt2ZXVkZjkx
        QnJHQXlHUGlYelZQVUFZY2Y2cmF2TzFiU2NrT0FrbjFSeE0KbTj42cgkWH4flIz9
        vIOWqDjf78SiQjmxVSRdhvbvDN+a+anB5XHOW+gw0U9ObXgqtiyGrDGam1s7JN+0
        uvCdgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE13M29lZyBUYVFo
        R29MTVErMGNXcjdBTlp4OVhkS2dyY1NyK0c0bGVsSURua3hDNUMwCnUxNHU5TGU2
        bWRGK0tSSWYzTDJxVnVmdzIwd0ZFT1pYK3hSTlBSZHBUYkUKLS0tIFZmVFBOczhK
        RTY3OU5ZclFsc0psWHZFZGNiTXFBVDF0Z0N2WE5OaFlJRDgK4vkrcSZZ3CAvLcji
        VO7mR5aZSVqnMOOB3HgGCVDW4lpdnEtldQD3VfJgZ1hZWlPodb67dUMaLUVbQ5dw
        KWW2+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvpEKtai3RlmudK/D6U4gj+N9w5Zk2QG5tqmjxEqkw/
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNqVWdVdyBGcExj
        KzkrWTFUeklpVklkRUY3dU1oSTNxMlQxaitleFZyZjBraUoyZUNVCjJIU2hhVytn
        V3dVV3NJZzhYYVZXcjdnektrVURGSFFDRlJDWEN2SmpOcE0KLS0tIE41ejJ5STdQ
        cHB0R0hubisvNG40bXhLZk5LdExlb3VodndQMDhTN1IrREUK7SXieIYAhKNBsiFD
        8VRkPdhmw4Np8DOJs71meG2FzVWiTEHMJ/vV5+8lWbsHHAeSb90gL51lGsVfQgw/
        9bLmxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0qIjPSoPxrWtME6jXPYkToLL5wrKi2NPvwdeFafwzb
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUS85L1U1d0s4dzRQVVNk
        SmcvVFhESDhwUU81UFJSUzdIYmQxTzB3dkVFCjA2eHVyVXkzczV3akl2UlRqRDdz
        amdkclRXamN4OGwrcHdZYlVsRkR6UEEKLS0tIGt4REM3bk5EemFFcDY2MDFob0pN
        UzFKTStHODc2YlhxYWJWVk5OZGROOGcKIYe7OIovxvhG+ttahyYRjW0JSW17DlX5
        I0QQZRQemTtsEXQTe/RNtmLHRg0BjcjS6KUuGRNyMP8LiSl1ExFTZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T15:04:37Z"
  mac: ENC[AES256_GCM,data:rjokq8eSw9xNSlhWCXupKOFyJc8uAQd5UgEeSE3UY8aF77pm0AQ/FiWkbV0+sqsm051BfAxp0MJlZwoVtGmg3T6GDM8sWOINPvaAtlKwTqS1P9jehVsAyk+Abtn8ANF9H9qKY8Qf+Pm5S/Mgjs0We/CJ31lOpv+hFfl+joXg/oc=,iv:tlrw1fFQbSvNDMEAybbku2rGQrBrXiVXF0VIaZdCrr8=,tag:aqclnkf4ZhPVMOsYhev7UA==,type:str]
  version: 3.13.2
