apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: allure-report
  namespace: argocd
  labels:
    team: releng
    app: allure-report
spec:
  project: allure-report
  source:
    repoURL: https://github.com/kdion-nrao/gitops-envs-test.git
    targetRevision: HEAD
    # path: apps/allure-report
    path: apps/releng-allure-report
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - $values/values/apps/allure-report/common/values.yaml
        - $values/values/apps/allure-report/common/secrets.enc.yaml
        - $values/values/apps/allure-report/variants/local/values.yaml
        - $values/values/apps/allure-report/envs/local/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: allure-report
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
