color: blue

contextPath: /dev

image:
  pullPolicy: Always
  tag: 'sha-8d72d86'

ingress:
  tls:
    - hosts:
        - dummy.localhost
  hosts:
    - host: dummy.localhost
      paths:
        - path: /dev
          pathType: Prefix
