apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: argocd
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: github-token
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: scm-creds
      data:
        token: '{{ .token }}'
  data:
  - secretKey: token
    remoteRef:
      key: /repos/github-token
      version: v1
