apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: keeper-secretstore
  namespace: external-secrets
spec:
  provider:
    keepersecurity:
      authRef:
        name: ksm-config-secret
        key: ksmConfig
        namespace: external-secrets
