apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reportportal
  namespace: argocd
  labels:
    team: releng
    app: reportportal
spec:
  project: reportportal
  sources:
  - repoURL: https://k8s.reportportal.io
    chart: reportportal
    targetRevision: 26.8.12
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - $values/values/apps/reportportal/common/values.yaml
        - $values/values/apps/reportportal/common/secrets.enc.yaml
  - repoURL: https://github.com/kdion-nrao/gitops-envs-test.git
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: reportportal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
