apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/actions/actions-runner-controller
    path: charts/gha-runner-scale-set-controller
    targetRevision: 74cfc3855ead2760f0b11d49feacf8d88bcb8ae0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
