apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arc-runner-environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: local
            minRunners: "0"
            maxRunners: "3"
  template:
    metadata:
      name: 'arc-runner-set-{{environment}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/actions/actions-runner-controller'
        path: charts/gha-runner-scale-set
        targetRevision: gha-runner-scale-set-0.14.2
        helm:
          values: |
            githubConfigUrl: "https://github.com/kdion-nrao/gitops-envs-test/"
            githubConfigSecret: arc-github-secret
            
            runnerScaleSetName: "aws-arc-runner-{{environment}}"
            
            minRunners: {{minRunners}}
            maxRunners: {{maxRunners}}

            controllerServiceAccount:
              name: "arc-controller-gha-rs-controller"
              namespace: "arc-systems"

            containerMode:
              type: "kubernetes-novolume"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'arc-runners-{{environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
