apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dummy-app-pr-previews
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
      ## We effectively want an AND merge - where only the staging cluster only
      ## creates apps for the PRs tagged with 'preview'
    - merge:
        mergeKeys:
          ## The two generators don't share any values by default, so we add
          ## an arbitrary value to merge on.
          - values.anchor
        generators:
          ## Start with the staging cluster, so this won't apply on prod
          - clusters:
              selector:
                matchLabels:
                  releng.nrao/cluster-role: 'staging'
              values:
                anchor: 'yes'
          ## Merge in the pull request generator values
          - pullRequest:
              github:
                owner: nrao
                repo: dummy-app
                tokenRef:
                  secretName: github-token
                  key: token
                labels:
                  - preview
              requeueAfterSeconds: 60
              values:
                anchor: 'yes'
      selector:
        ## finally, check for the existence of {{ .number }}
        ## in case there were no PRs tagged
        matchExpressions:
          - key: number
            operator: Exists
  template:
    metadata:
      name: 'dummyapp-pr-{{.number}}'
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.github: ""
    spec:
      project: releng-dummyapp-demo
      sources:
      - path: helm-dummyapp
        repoURL: https://github.com/nrao/dummy-app.git
        targetRevision: '{{.head_sha}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - $values/values/apps/dummy-app/common/values.yaml
            - $values/values/apps/dummy-app/common/secrets.enc.yaml
            - $values/values/apps/dummy-app/variants/local/values.yaml
          values: |
            contextPath: '/pr-{{.number}}'
            image:
              pullPolicy: Always
              tag: 'pr-{{.number}}'
            ingress:
              tls:
                - hosts:
                    - 'dummy-preview.localhost'
              hosts:
                - host: 'dummy-preview.localhost'
                  paths:
                    - path: '/pr-{{.number}}'
                      pathType: Prefix
      - repoURL: https://github.com/kdion-nrao/gitops-envs-test.git
        targetRevision: HEAD
        ref: values
      destination:
        server: '{{ .server }}'
        namespace: dummyapp-preview-pr-{{.number}}
      syncPolicy:
        automated:
          enabled: false
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/instance: dummyapp-pr-{{.number}}
          annotations:
             argocd.argoproj.io/tracking-id: dummyapp-pr-{{.number}}:/Namespace:dummyapp-preview-pr-{{.number}}/dummyapp-preview-pr-{{.number}}
        syncOptions:
          - CreateNamespace=true
