sampleVar: COMMON sampleVar

## color is the color to use for the webpage background. Valid values are the Solarized colors: https://ethanschoonover.com/solarized/
color: magenta

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: "1.1.5"

imageCredentials:
  registry: ghcr.io
  username: kdion-nrao

podLabels: {}

service:
  type: ClusterIP
  port: 80
