color: blue

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: 'dummy.localhost'
      paths:
        - path: /
          pathType: Prefix
  tls: []
