sampleVar: COMMON sampleVar

## color is the color to use for the webpage background. Valid values are the Solarized colors: https://ethanschoonover.com/solarized/
color: magenta

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: "nrao.repo.sonatype.app/cicdpilot/releng/dummy_app"
  tag: "1.1.5"

imageCredentials:
  registry: nrao.repo.sonatype.app

podLabels: {}

service:
  type: ClusterIP
  port: 80
