apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
data:
  token: ENC[AES256_GCM,data:FBD8LM7JgdMwbZaAutBg518rci57mt1nkfpCgKv+ISfEVd7DzdK5MmJ1VH48kbeq3sgukI4Bgyg=,iv:wNvS3CpbGwS6ywH1993QB2Zhz8dtSUBum4DciYJpCyA=,tag:wO8Ip6N9eAh0MwkAeIfzEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdQL2lMQSBWZHlZ
        WkR2VDdQRFBrczNKWHp0aWk1c3IzN3JMK0wrY2pvV3A3aTlYeVE0CnZMbzNMSjBm
        ZXVlMnV0QU8wOVlmVUUxTUt5a1hCMzQ5ZThKV2NlejV6MncKLS0tIHRMWU1VUDNJ
        NUNFeHRmT3ZuSC9GdHZRZ1hpcis3VTJRZWw4dXcrSXg5NjQKQJv4tXRih0HSkIH1
        gEtTMHMXsYY/SoSgk9JJRHUYr52+qmD3Ufom33fYhmKgnw4YvFTRGS7tgZb0LDnv
        9aF/Zw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpycNP1F4baBJ9N7Xn+IlgVxiGo0KkRwU7hGcXEQ8DE
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRHN6VFU5RCtiajF4alVC
        YmVDMCt3TFhiU05GTENSUFQ3MS9ORzUvVkd3CnJQSkJGZFNuVmFZWW5USkJtb254
        eXVGY1NmVEJXMmtmV3JOSDZ1cU5tNHMKLS0tIDhzUXhkS0QzbUkyRTdFRTZYaStZ
        OW5GSlo5ZzUrZHE4dzBaNTlOeHJtOEkKypEYm+FcqdJuYkBduay1H/bC1Ml8I2Pu
        eF+MXY+S7wpQEoPk7xF7wrJSIqgG0/gytxHNulqFE9nSBbExfMY30g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m2la56dk3rvfezkfpwkpes6zq69jcl97tx05d0xq3z64pkkmlf6qa54hu4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T15:04:37Z"
  mac: ENC[AES256_GCM,data:rjokq8eSw9xNSlhWCXupKOFyJc8uAQd5UgEeSE3UY8aF77pm0AQ/FiWkbV0+sqsm051BfAxp0MJlZwoVtGmg3T6GDM8sWOINPvaAtlKwTqS1P9jehVsAyk+Abtn8ANF9H9qKY8Qf+Pm5S/Mgjs0We/CJ31lOpv+hFfl+joXg/oc=,iv:tlrw1fFQbSvNDMEAybbku2rGQrBrXiVXF0VIaZdCrr8=,tag:aqclnkf4ZhPVMOsYhev7UA==,type:str]
  version: 3.13.2
