name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Use-ARC:
    runs-on: aws-arc-runner-local
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_REF: ${{ github.ref }}
        run: |
          echo "🎉 This job uses runner scale set runners!"
          echo "Repo: $GH_REPO, Ref: $GH_REF"
